# Autogenerated wrapper script for GAP_pkg_kbmag_jll for x86_64-linux-musl
export autcos, autgroup, fsaand, fsaandnot, fsabfs, fsaconcat, fsacount, fsaenumerate, fsaexists, fsafilter, fsagrowth, fsalabmin, fsalequal, fsamin, fsanot, fsaor, fsaprune, fsareverse, fsastar, fsaswapcoords, gpaxioms, gpcheckmult, gpchecksubwa, gpcomp, gpdifflabs, gpgenmult, gpgenmult2, gpgeowa, gpmakefsa, gpmakesubwa, gpmicomp, gpmigenmult, gpmigenmult2, gpmigmdet, gpmimult, gpmimult2, gpminkb, gpmult, gpmult2, gpsubpres, gpsubwa, gpwa, kbprog, kbprogcos, makecosfile, midfadeterminize, nfadeterminize, ppgap, ppgap4, wordreduce

JLLWrappers.@generate_wrapper_header("GAP_pkg_kbmag")
JLLWrappers.@declare_executable_product(autcos)
JLLWrappers.@declare_executable_product(autgroup)
JLLWrappers.@declare_executable_product(fsaand)
JLLWrappers.@declare_executable_product(fsaandnot)
JLLWrappers.@declare_executable_product(fsabfs)
JLLWrappers.@declare_executable_product(fsaconcat)
JLLWrappers.@declare_executable_product(fsacount)
JLLWrappers.@declare_executable_product(fsaenumerate)
JLLWrappers.@declare_executable_product(fsaexists)
JLLWrappers.@declare_executable_product(fsafilter)
JLLWrappers.@declare_executable_product(fsagrowth)
JLLWrappers.@declare_executable_product(fsalabmin)
JLLWrappers.@declare_executable_product(fsalequal)
JLLWrappers.@declare_executable_product(fsamin)
JLLWrappers.@declare_executable_product(fsanot)
JLLWrappers.@declare_executable_product(fsaor)
JLLWrappers.@declare_executable_product(fsaprune)
JLLWrappers.@declare_executable_product(fsareverse)
JLLWrappers.@declare_executable_product(fsastar)
JLLWrappers.@declare_executable_product(fsaswapcoords)
JLLWrappers.@declare_executable_product(gpaxioms)
JLLWrappers.@declare_executable_product(gpcheckmult)
JLLWrappers.@declare_executable_product(gpchecksubwa)
JLLWrappers.@declare_executable_product(gpcomp)
JLLWrappers.@declare_executable_product(gpdifflabs)
JLLWrappers.@declare_executable_product(gpgenmult)
JLLWrappers.@declare_executable_product(gpgenmult2)
JLLWrappers.@declare_executable_product(gpgeowa)
JLLWrappers.@declare_executable_product(gpmakefsa)
JLLWrappers.@declare_executable_product(gpmakesubwa)
JLLWrappers.@declare_executable_product(gpmicomp)
JLLWrappers.@declare_executable_product(gpmigenmult)
JLLWrappers.@declare_executable_product(gpmigenmult2)
JLLWrappers.@declare_executable_product(gpmigmdet)
JLLWrappers.@declare_executable_product(gpmimult)
JLLWrappers.@declare_executable_product(gpmimult2)
JLLWrappers.@declare_executable_product(gpminkb)
JLLWrappers.@declare_executable_product(gpmult)
JLLWrappers.@declare_executable_product(gpmult2)
JLLWrappers.@declare_executable_product(gpsubpres)
JLLWrappers.@declare_executable_product(gpsubwa)
JLLWrappers.@declare_executable_product(gpwa)
JLLWrappers.@declare_executable_product(kbprog)
JLLWrappers.@declare_executable_product(kbprogcos)
JLLWrappers.@declare_executable_product(makecosfile)
JLLWrappers.@declare_executable_product(midfadeterminize)
JLLWrappers.@declare_executable_product(nfadeterminize)
JLLWrappers.@declare_executable_product(ppgap)
JLLWrappers.@declare_executable_product(ppgap4)
JLLWrappers.@declare_executable_product(wordreduce)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        autcos,
        "bin/autcos",
    )

    JLLWrappers.@init_executable_product(
        autgroup,
        "bin/autgroup",
    )

    JLLWrappers.@init_executable_product(
        fsaand,
        "bin/fsaand",
    )

    JLLWrappers.@init_executable_product(
        fsaandnot,
        "bin/fsaandnot",
    )

    JLLWrappers.@init_executable_product(
        fsabfs,
        "bin/fsabfs",
    )

    JLLWrappers.@init_executable_product(
        fsaconcat,
        "bin/fsaconcat",
    )

    JLLWrappers.@init_executable_product(
        fsacount,
        "bin/fsacount",
    )

    JLLWrappers.@init_executable_product(
        fsaenumerate,
        "bin/fsaenumerate",
    )

    JLLWrappers.@init_executable_product(
        fsaexists,
        "bin/fsaexists",
    )

    JLLWrappers.@init_executable_product(
        fsafilter,
        "bin/fsafilter",
    )

    JLLWrappers.@init_executable_product(
        fsagrowth,
        "bin/fsagrowth",
    )

    JLLWrappers.@init_executable_product(
        fsalabmin,
        "bin/fsalabmin",
    )

    JLLWrappers.@init_executable_product(
        fsalequal,
        "bin/fsalequal",
    )

    JLLWrappers.@init_executable_product(
        fsamin,
        "bin/fsamin",
    )

    JLLWrappers.@init_executable_product(
        fsanot,
        "bin/fsanot",
    )

    JLLWrappers.@init_executable_product(
        fsaor,
        "bin/fsaor",
    )

    JLLWrappers.@init_executable_product(
        fsaprune,
        "bin/fsaprune",
    )

    JLLWrappers.@init_executable_product(
        fsareverse,
        "bin/fsareverse",
    )

    JLLWrappers.@init_executable_product(
        fsastar,
        "bin/fsastar",
    )

    JLLWrappers.@init_executable_product(
        fsaswapcoords,
        "bin/fsaswapcoords",
    )

    JLLWrappers.@init_executable_product(
        gpaxioms,
        "bin/gpaxioms",
    )

    JLLWrappers.@init_executable_product(
        gpcheckmult,
        "bin/gpcheckmult",
    )

    JLLWrappers.@init_executable_product(
        gpchecksubwa,
        "bin/gpchecksubwa",
    )

    JLLWrappers.@init_executable_product(
        gpcomp,
        "bin/gpcomp",
    )

    JLLWrappers.@init_executable_product(
        gpdifflabs,
        "bin/gpdifflabs",
    )

    JLLWrappers.@init_executable_product(
        gpgenmult,
        "bin/gpgenmult",
    )

    JLLWrappers.@init_executable_product(
        gpgenmult2,
        "bin/gpgenmult2",
    )

    JLLWrappers.@init_executable_product(
        gpgeowa,
        "bin/gpgeowa",
    )

    JLLWrappers.@init_executable_product(
        gpmakefsa,
        "bin/gpmakefsa",
    )

    JLLWrappers.@init_executable_product(
        gpmakesubwa,
        "bin/gpmakesubwa",
    )

    JLLWrappers.@init_executable_product(
        gpmicomp,
        "bin/gpmicomp",
    )

    JLLWrappers.@init_executable_product(
        gpmigenmult,
        "bin/gpmigenmult",
    )

    JLLWrappers.@init_executable_product(
        gpmigenmult2,
        "bin/gpmigenmult2",
    )

    JLLWrappers.@init_executable_product(
        gpmigmdet,
        "bin/gpmigmdet",
    )

    JLLWrappers.@init_executable_product(
        gpmimult,
        "bin/gpmimult",
    )

    JLLWrappers.@init_executable_product(
        gpmimult2,
        "bin/gpmimult2",
    )

    JLLWrappers.@init_executable_product(
        gpminkb,
        "bin/gpminkb",
    )

    JLLWrappers.@init_executable_product(
        gpmult,
        "bin/gpmult",
    )

    JLLWrappers.@init_executable_product(
        gpmult2,
        "bin/gpmult2",
    )

    JLLWrappers.@init_executable_product(
        gpsubpres,
        "bin/gpsubpres",
    )

    JLLWrappers.@init_executable_product(
        gpsubwa,
        "bin/gpsubwa",
    )

    JLLWrappers.@init_executable_product(
        gpwa,
        "bin/gpwa",
    )

    JLLWrappers.@init_executable_product(
        kbprog,
        "bin/kbprog",
    )

    JLLWrappers.@init_executable_product(
        kbprogcos,
        "bin/kbprogcos",
    )

    JLLWrappers.@init_executable_product(
        makecosfile,
        "bin/makecosfile",
    )

    JLLWrappers.@init_executable_product(
        midfadeterminize,
        "bin/midfadeterminize",
    )

    JLLWrappers.@init_executable_product(
        nfadeterminize,
        "bin/nfadeterminize",
    )

    JLLWrappers.@init_executable_product(
        ppgap,
        "bin/ppgap",
    )

    JLLWrappers.@init_executable_product(
        ppgap4,
        "bin/ppgap4",
    )

    JLLWrappers.@init_executable_product(
        wordreduce,
        "bin/wordreduce",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
